# Generated by Django 4.0.3 on 2022-03-26 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BusModel', models.CharField(default=None, max_length=20)),
                ('HasAc', models.BooleanField()),
                ('seatStructure', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BusNumber', models.CharField(default=None, max_length=10)),
                ('CoachNo', models.CharField(default=None, max_length=10, null=True)),
                ('Active', models.BooleanField(default=True)),
                ('Price', models.DecimalField(decimal_places=2, default=None, max_digits=5)),
                ('BusStructure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BusSchedule.busstructure')),
            ],
        ),
    ]
