# Generated by Django 4.0.2 on 2022-03-27 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('BusNumber', models.CharField(default=None, max_length=10, primary_key=True, serialize=False)),
                ('CoachNo', models.CharField(default=None, max_length=10, null=True)),
                ('Active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartCity', models.CharField(default=None, max_length=20)),
                ('EndCity', models.CharField(default=None, max_length=20)),
                ('Price', models.DecimalField(decimal_places=2, default=None, max_digits=5)),
                ('Class', models.CharField(default=None, max_length=20)),
                ('Bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BusSchedule.bus')),
            ],
        ),
        migrations.CreateModel(
            name='BusStructure',
            fields=[
                ('BusModel', models.CharField(default=None, max_length=20, primary_key=True, serialize=False)),
                ('HasAc', models.BooleanField()),
                ('seatStructure', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.CharField(default=None, max_length=10)),
                ('ArrivalPoint_and_time', models.JSONField()),
                ('DepurturePoint_and_time', models.JSONField()),
                ('BusSchedule', models.ManyToManyField(through='BusSchedule.BusSchedule', to='BusSchedule.Bus')),
            ],
        ),
        migrations.AddField(
            model_name='busschedule',
            name='Schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BusSchedule.schedule'),
        ),
        migrations.AddField(
            model_name='bus',
            name='BusStructure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BusSchedule.busstructure'),
        ),
        migrations.AddIndex(
            model_name='busschedule',
            index=models.Index(fields=['StartCity', 'EndCity'], name='BusSchedule_StartCi_24adc9_idx'),
        ),
    ]
