# Generated by Django 4.0.3 on 2022-03-26 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BusSchedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartCity', models.CharField(default=None, max_length=20)),
                ('EndCity', models.CharField(default=None, max_length=20)),
                ('Bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BusSchedule.bus')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.CharField(default=None, max_length=10)),
                ('ArrivalPoint_and_time', models.JSONField()),
                ('DepurturePoint_and_time', models.JSONField()),
                ('BusSchedule', models.ManyToManyField(through='BusSchedule.BusSchedule', to='BusSchedule.bus')),
            ],
        ),
        migrations.AddField(
            model_name='busschedule',
            name='Schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BusSchedule.schedule'),
        ),
    ]
